### ISSUE TITLE
eagerの表現を統一したい。

### ISSUE THREAD

**Issue by chie8842** [tfug/proofreading#17]
私のPR（マージ済み）では、`Eager Execution`で統一しています。
以下PRでは、`eager実行`、`eager 実行`、`eagerモード`の3種類が出てきます。
https://github.com/tensorflow/docs/pull/563
以下PRでは、`eager execution`となっています。
https://github.com/tensorflow/docs/pull/698

どれかに統一したいです。
個人的には、中国語が`Eager Execution`で統一されているようなので、`Eager Execution`にしたいです。

**Comment by katoosky** [comment]
このファイルのタイトルが`Eager Execution`となっていて、
一つの名詞のように扱っているように思われるので、
自分は`Eager Execution`で統一していいと思います。
https://github.com/tensorflow/docs/blob/f058581102cc1df25a62e2456a2d59d579209f39/site/en/guide/eager.ipynb

その場合、他の`eager ~`についてはどう扱いましょうか。

**Comment by chie8842** [comment]
`Eager Execution`に統一でいいなら、すでにマージされているものに関してはわたしの方で変更PR投げようと思います！

**Comment by AseiSugiyama** [comment]
Eager Execution でいいと思います！

**Comment by ohtaman** [comment]
私も Eager Execution で良いと思います。
ただ、eagerモード はたぶん eager mode の訳なので、本当に eager execution と同じかは確認したほうが良さそう。

**Comment by AseiSugiyama** [comment]
なお、「Eager 実行」「Eager モード」はこのブログポストに従った結果です。
https://developers-jp.googleblog.com/2019/03/effective-tensorflow-20.html

**Comment by chie8842** [comment]
なるほどー、佐藤かずのりさんが書いてるんですね。
公式ドキュメントでの記述はのちのち様々な文章に影響を与える可能性があるので、表記は真面目に決めたいですね。
コミュニティメンバだけで決めるのもよくない気がしてきました。

**Comment by chie8842** [comment]
慎重すぎ？

**Comment by AseiSugiyama** [comment]
一応他にも先行事例を調べたところ、"Eager" という概念自体は "Lazy" と対になり、日本語では "Eager evaluation / Lazy evaluation" を「先行評価 / 遅延評価」とする訳が定着しているようですね。
とはいえ、訳していない "Eager Execution" も定着しつつあるように思いますので、個人的には "Eager Execution" を推します。

**Comment by masa-ita** [comment]
私も"Eager Execution" で良いと思います。

ちなみに、「先行評価/遅延評価」にならった「先行実行/遅延実行」の使用例はないかと思いましたが、「先行実行」は事例が見つからず、「遅延実行」はMicrosoftのLINQのドキュメントにありました。
https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/linq/deferred-execution-example
ただし、これは "deferred execution" の訳にあてられており、対義語は "immediate execution" のようです。

**Comment by chie8842** [comment]
表記ゆれ統一PR投げた。
https://github.com/tensorflow/docs/pull/724

**Comment by AseiSugiyama** [comment]
マージされましたね 🎉

**Comment by chie8842** [comment]
ほんとだ！レビューありがとうございました！😄
