### ISSUE TITLE
Note: の表現を統一したい。

### ISSUE THREAD

**Issue by ohtaman** [tfug/proofreading#18]
Note: のままにする > いまのところ 9箇所
注: に訳す > いまのところ 8箇所

ちなみに Caution: はすべて(4箇所) 注意： に訳されている。

自分は Note: のままにしていたけど、 注: でもいいかも。

**Comment by yukinagae** [comment]
もし `Caution:` を `注意:` として訳してるなら、 `Note:` も `注:` に訳した方が統一感あるかなと思います。

**Comment by chie8842** [comment]
わたしも`注`に賛成ですー。（自分のはNoteになっている。）

**Comment by katoosky** [comment]
Cautionを訳しているなら`注：`訳すのは賛成です。
ただ、`注意：`と混同しないかだけ心配してます。`注釈：`としても微妙ですし
（そもそもどっちも見てもらいたいものなので混同しても問題ない感はある）

**Comment by masa-ita** [comment]
この件ですが、@lamberta さんから、下記のPRで、Note: はサイト上の callout boxes (吹き出し) のスタイル指示になっているので、翻訳しないでほしいというコメントがありましたね。

https://github.com/tensorflow/docs/pull/711

**Comment by ohtaman** [comment]
なるほど。では Note: Caution: Warning: などは訳さないほうが良さそうですね。

**Comment by lamberta** [comment]
Hi all,

For reference, these are all the available notice styles to create callout boxes on the website. The following should *not* get translated:
`Note:`, `Caution:`, `Warning:`, `Key Point:`, `Key Term:`, `Objective:`, `Success:`, and `Dogfood:`

We don't use them all on tensorflow.org. To create a callout box, these tags are used at the beginning of the line.

Thanks for looking at this!
