### ISSUE TITLE
補完がきかないのを何とかしたい

### ISSUE THREAD

**Issue by sfujiwara** [tfug/proofreading#32]
`docs` の下に `proofreading` を clone して使っていると、 docker run でひとつ上のディレクトリをマウントする必要があるので `./bin/run-check hoge` って打つときに `hoge` のところで補完がきかないのが結構つらかった

何か良い対策を考えてちょっと校正を良い感じにしたいところ

**Comment by sfujiwara** [comment]
あと翻訳者がフォークしたリポジトリをひとつずつ `git clone` して、その中で作業するのも大変だったので、次のようなコマンドでリポジトリとブランチを指定したら全部ガッとやってくれる感じにしたらレビュアーの負担だいぶ減りそう:

```bash
clone git@github.com:tfug/proofreading.git
cd proofreading

# ./bin/run <repository name> <branch name>
./bin/run sfujiwara/docs translate-hoge
```

**Comment by chie8842** [comment]
> あと翻訳者がフォークしたリポジトリをひとつずつ git clone して、その中で作業するのも大変だった

なるほど、これはレビューやってる人からするとたしかに辛いですね。
よさそうです！

**Comment by sfujiwara** [comment]
#33 でまとめてどばばっとやるようにしたので close
