### ISSUE TITLE
Docker image の管理

### ISSUE THREAD

**Issue by sfujiwara** [tfug/proofreading#4]
@ohtaman @chie8842 Docker image を作るなら Docker Hub のリポジトリと紐付ける専用の GitHub リポジトリ欲しくないですか？
こんな感じのやつ: https://github.com/vvakame/docker-review

その場合リポジトリ構成どうしようかなーと悩んでいて、どうすると良さそうか意見が欲しいです。

## Plan 1

- `tfug/docker-proofreading` という GitHub リポジトリを新しく作る
- `tfug/proofreading` とは共存する形

## Plan 2

- `tfug/proofreading` を Docker Hub と紐付けるリポジトリにしちゃう
- 好みっぽいけど名前は `tfug/docker-proofreading` とかに rename した方がわかりやすいかも
- その場合ここに `Makefile` とかを置くと不自然になっちゃうので次のようにすると良いかも？
  - `docker run-v ... -e INPUT=doc/file/path.ipynb tfug/proofreading` とかで実行できるようにする
  - `redpen-conf.xml` とかも Docker image に突っ込んじゃって `docker run` だけで完結するようにしておく
  - 本家の[ガイドライン](https://github.com/tensorflow/docs/tree/master/site/ja)に実行のコマンドを書く

**Comment by chie8842** [comment]
# リポジトリを分けるかどうかについて
個人的には、Dockerfileはproofreadingリポジトリに同梱でいいと思います。
TensorflowもDockerfileはTensorflow本体と同じリポジトリで管理されています。
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dockerfiles
他のOSSソフトウェアもわたしが知るものは、Dockerfileとソースコードを同じリポジトリで管理している場合が多いように思います。

# 設定ファイルをDockerイメージに含むかどうか
個人的には、イメージに設定ファイルは含まないほうが良いと考えています。
今後レビューが活発になっていくと、設定ファイルの更新頻度は多くなっていくことが予想されます。最新のDockerイメージでレビューする必要がでてくるため、設定ファイルが更新されるごとに一度ローカルのDockerイメージを一度purgeしてDocker pullするという運用になるため、毎回Dokcer pullするためのネットワーク及び時間的コストがかかるためです。

**Comment by sfujiwara** [comment]
とりあえず↑の方針でいくので閉じますよ〜
