### ISSUE TITLE
Consider variable depth of directory structure

### ISSUE THREAD

**Issue by sfujiwara** [tfug/proofreading#6]
In `proofreading.sh`, we assume a directory structure such as `site/ja/tutorials/keras/hoge.ipynb` as below:

https://github.com/tfug/proofreading/blob/8f89a89a0704299f0b5f58c63eb64dc9eec537bf/proofreading.sh#L22

In some documents, however, they adopt different structure which is more shallow than the one we expect.
An example is here:
https://github.com/tensorflow/docs/tree/master/site/en/install

**Comment by chie8842** [comment]
すみません、このIssue気づかずPR作ってしまいました。
https://github.com/tfug/proofreading/pull/7

5階層目までのipynbだけとってくるようにしましたが、
現在他のディレクトリ構造でこれだととってこれないものがあるかあとで確認しますー。

**Comment by sfujiwara** [comment]
#7 #10 あたりで色々直ったのでおっけー
